### PR TITLE
basket ball animation 

### PR DESCRIPTION
**Pull request by RAHULBAWA777**
adding basket ball animation project

closses issue - #42

### CODE REVIEW

**Review by VidhiBhatt01 — COMMENTED** [review]
https://deploy-preview-53--cozy-pastelito-ffe9b3.netlify.app/projects/basket%20ball%20animation/

Are you sure that the code is not plagiarised?

**Comment by RAHULBAWA777** [comment]
> https://deploy-preview-53--cozy-pastelito-ffe9b3.netlify.app/projects/basket%20ball%20animation/
> 
> Are you sure that the code is not plagiarised?

yes it's 100% genuine ... just took the idea from Instagram posts and codepen 

if you still feel it's plag.... let me know ...I should make a new issue in that case :)

**Comment by RAHULBAWA777** [comment]
@VidhiBhatt01 please let me know... I got MSTs from monday... I won't be able to give time later

**Comment by VidhiBhatt01** [comment]
No worries, it's fine. Good luck for your MSTs!

**Comment by RAHULBAWA777** [comment]
> No worries, it's fine. Good luck for your MSTs!

hey @VidhiBhatt01,  thanks for taking out time and reviewing my PRs......really appreciate it.

**Pull request merged**
