### PR TITLE
Created a AI Image Generator Using HTML-CSS-JS

### PR DESCRIPTION
**Pull request by Robinrai2612**
@VidhiBhatt01 I have submitted the Pull Request, and I would greatly appreciate it if you could take a moment to review it. If everything appears to be in order, I kindly request you to merge it. Thank you!

### CODE REVIEW

**Comment by VidhiBhatt01** [comment]
Link the issue in description

**Review by VidhiBhatt01 — APPROVED** [review]

**Comment by Robinrai2612** [comment]
Fixes: #101 AI Image Generator Website

This application lets users generate AI images from prompts and choose the quantity, with easy individual downloads.

@VidhiBhatt01 I have linked the issue in the description. Kindly merge it.

**Comment by Robinrai2612** [comment]
Fixes : #101 AI Generator Website

This application lets users generate AI images from prompts and choose the quantity, with easy individual downloads, all powered by advanced AI technology.

@VidhiBhatt01 I have linked the issue

**Comment by Robinrai2612** [comment]
@VidhiBhatt01 Please merge the pull request, as it has not been merged yet.

**Comment by Robinrai2612** [comment]
@VidhiBhatt01 Please merge the pull request, as it has not been merged yet.

**Pull request merged**
