### PR TITLE
Added Invisible Cloak Using OpenCV

### LINKED ISSUE #116: Invisible Cloak using OpenCV
@VidhiBhatt01 I would like to work on this issue. Please assign it to me.

### PR DESCRIPTION
**Pull request by Robinrai2612**
fixes: #116 

@VidhiBhatt01 I have made the changes and hav
pic1
e also added the images. Please review them and merge the changes.

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Link issue, attach photo for how it looks in description. I don't think this is related to frontend. Thoughts?

**Comment by Robinrai2612** [comment]
@VidhiBhatt01 Indeed, it's not related to the frontend; it's based on OpenCV. I will be attaching the photos to it.

**Comment by Robinrai2612** [comment]
fixes : #117 

@VidhiBhatt01 I have made the changes and have also added the image. Please review them and merge the changes.

**Comment by Robinrai2612** [comment]
fix: #116 

@VidhiBhatt01 I have made the changes and have also added the images. Please merge the changes.

**Comment by Robinrai2612** [comment]
@VidhiBhatt01 I have made the changes and have also added the images. Please merge the changes.

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Photo should be added in PR description, not in commit

**Comment by Robinrai2612** [comment]
pic1

@VidhiBhatt01 I have added the pic in the description.

**Review by VidhiBhatt01 — APPROVED** [review]

**Pull request merged**
