### PR TITLE
Added my amazon clone website

### PR DESCRIPTION
**Pull request by ilhamansari**
Issue #96 .

### CODE REVIEW

**Comment by ilhamansari** [comment]
Hey @VidhiBhatt01 , would you please merge my pr.

**Review by VidhiBhatt01 — APPROVED** [review]
Did you deploy it anywhere? If yes, please comment the link here..

**Comment by ilhamansari** [comment]
Actually I am currently working on responsiveness. I will make the website responsive , deploy it and then would surely comment down the link here.

**Comment by VidhiBhatt01** [comment]
Any updates?? There are many files in this commit that's why am asking for a deployed link @ilhamansari

**Comment by ilhamansari** [comment]
Okay @VidhiBhatt01 . Will deploy it within today and comment down the link here ASAP .

**Comment by ilhamansari** [comment]
@VidhiBhatt01 here you go with the link. https://ilhamansari.github.io/Amazon-clone/ 
Hope you like it.

**Pull request merged**
