### PR TITLE
Added dino game

### LINKED ISSUE #66: Dino Game
### Project Title :
Dino Game
### Project Description :
A simple, yet popular dinosaur game played on chrome built using HTML, JavaScript and CSS.

### PR DESCRIPTION
**Pull request by Akshata-Gunapache**
This is a simple clone of the very popular dinosaur game played on the browser.
This PR fixes #66 

image

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
image

The score keeps on increasing even after the game is over. This is most probably due to some error in Javascript logic. can you fix it?

**Comment by Akshata-Gunapache** [comment]
Ok, I will make the changes soon.
Thank You

**Comment by Akshata-Gunapache** [comment]
@VidhiBhatt01  Please review my changes. Thank You :)

**Comment by Akshata-Gunapache** [comment]
image

**Review by VidhiBhatt01 — APPROVED** [review]
Awesome, thanks for contributing!

**Pull request merged**
