### PR TITLE
WHAC-A-MOLE game files added

### LINKED ISSUE #27: Whac - a - mole game
Creating a whac - a - mole game using html css ans js

### PR DESCRIPTION
**Pull request by CS50X-RGB**
Closes #27

### CODE REVIEW

**Comment by CS50X-RGB** [comment]
@VidhiBhatt01 plz review this pr

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
image
Enhance the UI and make it responsive for all screen sizes

**Comment by CS50X-RGB** [comment]
Ookay

**Comment by CS50X-RGB** [comment]
@VidhiBhatt01 i am not able to make the grid responsive 🥲 what should I do now I tried a lot

**Comment by CS50X-RGB** [comment]
Becoz in that case i have to change the grid size which will messing everything in the code can u help??

**Comment by VidhiBhatt01** [comment]
@CS50X-RGB no worries, I will create an issue for this. Someone else will fix it : )

**Comment by CS50X-RGB** [comment]
Ok thanks 😊

**Pull request merged**
