### PR TITLE
Book Store Website

### PR DESCRIPTION
**Pull request by aytida0606**
Book Store
 #33

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
image

 Add some space at the start

**Comment by VidhiBhatt01** [comment]
https://deploy-preview-34--cozy-pastelito-ffe9b3.netlify.app/projects/book%20store/

**Comment by aytida0606** [comment]
book store

**Comment by aytida0606** [comment]
@VidhiBhatt01 changes added

**Review by VidhiBhatt01 — APPROVED** [review]

**Pull request merged**
